const routes = {
    home: '/',
    following: '/following',
    profile: '/@:nickname',
    upload: '/upload',
    search: '/search',
    live: '/live',
    shop: '/shop',
    blogdetails: '/blogdetails',
    contact: '/contact',
    signup: '/signup',
    signin: '/signin',
    productDetail: '/ProductDetail',
    cart: '/Cart',
    checkout: '/CheckOut',
    artistProfile: '/Profile',
    artistOrder: '/Profile/ArtistOrder',
    createArtWork: '/Profile/Create',
    artistArtWork: '/Profile/MyArtwork',
    artworkOrdered: '/Profile/ArtworkOrdered',
    orderCompleted: '/Profile/OrderCompleted',
    requestArtwork: '/Profile/RequestArtwork',
    wishlist: '/Profile/Wishlist',
};

export default routes;
